# Generated by Django 5.1.7 on 2025-04-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosDiabetes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gravidez', models.IntegerField(default=0, verbose_name='Número de gestações')),
                ('glicose', models.IntegerField(verbose_name='Nível de glicose')),
                ('pressao', models.IntegerField(verbose_name='Pressão arterial diastólica')),
                ('espessura_pele', models.IntegerField(verbose_name='Espessura da dobra cutânea do tríceps')),
                ('insulina', models.IntegerField(verbose_name='Nível de insulina')),
                ('imc', models.FloatField(verbose_name='Índice de Massa Corporal')),
                ('pedigree', models.FloatField(verbose_name='Histórico familiar (Diabetes Pedigree Function)')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('resultado', models.IntegerField(default=0, verbose_name='Diagnóstico (0 = não, 1 = sim)')),
            ],
            options={
                'db_table': 'dados_diabetes',
            },
        ),
    ]
